uploadDir: /Users/jylee/IdeaProjects/Blog/upload
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: none
    properties:
      hibernate:
########        format_sql: true
########        use_sql_comments: true
#        show_sql: true
########logging.level:
########  org.hibernate.SQL: debug
#  orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
# org.hibernate.type: trace